### ISSUE TITLE
Design relelauta v.2.0

### ISSUE THREAD

**Issue by chiplet** [VerkkuUkkeli/Kiihdytin#13]
# Abbreviations
* EM - electromagnet

# TODO:
* [x] Measure EM inductance
* [x] Choose EM driver
  * Relay?
  * Load switch?
  * MOSFET?
* [ ] Indicator LEDs for EM drivers
  * [ ] Amplifiers for indicator led signal so that EM control signals are not loaded by the LEDs

## Electromagnet Specifications
* Resistance ~2 Ohm
* Inductance ~ 430 µH
=> Assuming 10A current, energy stored in inductor is E = 22mJ

## Electromagnet driver selection considerations
* High enough load current (around 10A, TBD)
* High enough power package to withstand generated heat
* Be able to withstand inductive "kicks" when switching off the electromagnet
  * Are external flywheel diodes required?
* Nice enough package for easy soldering

**Comment by chiplet** [comment]
# Electromagnet Driver Circuit

STM32 GPIO pins are a bit problematic, at least on the Blue Pill dev board. According to the reference manual, the GPIO pins should reset to floating input configuration. The configuration register contents match this configuration when inspecting memory. However, for whatever reason, when measured, the pin is pulled up to 3.3V. The boards were ordered from ebay so the issue might be that the MCU on the devboard is actually a clone which doesn't implement the floating state correctly.

Whatever the reason, this is problematic since when the pin is pulled to 3.3V an electromagnet controlled by the pin would turn on. This is not an issue after the pin has been configured as an output. However, when debugging with a breakpoint set to main, this would turn on **all** electromagnets by default at the same time and the electronics are not designed to handle that.

As a workaround I'm connecting an external 1k pull-down resistor which seems to pull the pin to around 0.7V when left "floating".

When using IRFZ44 MOSFET to drive the electromagnet there is no drain-source current (zero measurement in the mA range).

Some further measurements with 1k pulldown on GPIO:
floating input (uninitialized): pin voltage = 0.7V, ttl-converter high voltage = 0.7V
push-pull (initialized): pin voltage = 0V, ttl-converter high voltage = 0V (IIRC)
push-pull (initialized): pin voltage = 3.3V, ttl-converter high voltage = 3.8V

I.e. the output is not 5V due to the indicator LED, but for currents <= 10A this should be fine.

Turns out that I am not that smart :D. The 3.3V to 5V conversion circuit has a 10k pull-up resistor which explains many things...

Anyways the STM32 microcontroller GPIO can source up to 25mA, and IRLZ44N seems to both have a low enough gate threshold voltage for 3.3V logic level switching so the driver circuit can be as simple as driving both the indicator LED and MOSFET gate in parallel. There's should also be a pull-down resistor to make sure the MOSFET never turns accidentally before the GPIO are properly configured.
