### ISSUE TITLE
Motherboard firmware

### ISSUE THREAD

**Issue by kuuotto** [VerkkuUkkeli/Kiihdytin#15]
Develop the firmware for the motherboard which controls the electromagnets, reads the sensors and communicates with the PC command interface via a serial connection.

TODO:

- [ ] serial communication
- [ ] ...

**Comment by chiplet** [comment]
**TODO:**
- [ ] Serial communication
  - [ ] USART1 driver
  - [ ] Packet-based request-acknowledge command link
- [x] RGB animation (make it look like cool alien brains!)
- [ ] Sensor input interrupts
- [ ] Acceleration control sequencing
